django-ogunsoladebayoscrumy/ogunsoladebayoscrumy/urls.py
from os import name
from django.urls import path
from django.urls.conf import include
from . import views
app_name = 'ogunsoladebayoscrumy'
urlpatterns = [
    path('', views.get_grading_parameters, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal),
    path('addgoal/', views.add_goal),
    path('home/', views.home),
    path('accounts/', include('django.contrib.auth.urls'))

]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ogunsoladebayoscrumy/', include('ogunsoladebayoscrumy.urls')),
    path('websocket/', include('websocket.urls')),
]

ogunsoladebayoscrumy/urls.py
from os import name
from django.urls import path
from django.urls.conf import include
from . import views
app_name = 'ogunsoladebayoscrumy'
urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>', views.move_goal, name='movegoal'),
    path('addgoal/', views.add_goal, name='addgoal'),
    path('home/', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('slack/', views.slack)

]

django-ogunsoladebayoscrumy/ogunsoladebayoscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
...


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=255)


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=255)
    goal_id = models.IntegerField(unique=True)
    created_by = models.CharField(max_length=255)
    moved_by = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user',
                             on_delete=models.CASCADE)


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255)
    moved_from = models.CharField(max_length=255)
    moved_to = models.CharField(max_length=255)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

ogunsoladebayoscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
...


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=255)
    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=255)
    goal_id = models.IntegerField(unique=True)
    created_by = models.CharField(max_length=255)
    moved_by = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user',
                             on_delete=models.CASCADE)


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255)
    moved_from = models.CharField(max_length=255)
    moved_to = models.CharField(max_length=255)
    time_of_action = models.DateTimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

ogunsoladebayoscrumy/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import User, ScrumyGoals, GoalStatus


class SignupForm(forms.ModelForm):
    class Meta(object):
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email address'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Choose a username'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Enter a password to use'}),
        }


class CreateGoalForm(forms.ModelForm):
    class Meta(object):
        model = ScrumyGoals
        fields = ['goal_name', 'user', 'created_by', 'owner', 'goal_status']
        widgets = {
            'goal_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter goal name'}),
            'user': forms.Select(attrs={'class': 'form-control'}),
            'created_by': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Creator'}),
            'owner': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Owner'}),
            'goal_status': forms.Select(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CreateGoalForm, self).__init__(*args, **kwargs)
        self.fields['goal_status'].label_from_instance = lambda obj: "%s" % obj.status_name
        self.fields['goal_status'].queryset = GoalStatus.objects.filter(
            status_name='Weekly Goal')
        self.fields['user'].queryset = User.objects.filter(
            username=user)


class MoveGoalForm(forms.Form):
    goal_status = forms.ModelChoiceField(GoalStatus.objects.all(), widget = forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        role = kwargs.pop('role')
        user = kwargs.pop('user')
        goal_user = kwargs.pop('goal_user')
        super(MoveGoalForm, self).__init__(*args, **kwargs)
        self.fields['goal_status'].label_from_instance = lambda obj: "%s" % obj.status_name
        if role == 'Developer':
            if  str(goal_user) == str(user):
                self.fields['goal_status'].queryset = GoalStatus.objects.filter(
                    status_name__regex=r'^(Weekly|Daily|Verify)')
            else:
                self.fields['goal_status'].disabled = True
        elif role == 'Quality Assurance':
            if  str(goal_user) == str(user):
                pass
            else:
                self.fields['goal_status'].queryset = GoalStatus.objects.filter(
                    status_name__regex=r'^(Verify|Done)')
        elif role == 'Owner':
            if  str(goal_user) == str(user):
                pass
            else:
                self.fields['goal_status'].disabled = True
        elif role == 'Admin':
            pass

django-ogunsoladebayoscrumy/ogunsoladebayoscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import User, ScrumyGoals, ScrumyHistory, GoalStatus
from random import randint

# Create your views here.


def get_grading_parameters(request):
    return HttpResponse(ScrumyGoals.objects.get(goal_name='Learn Django').goal_name)


def move_goal(request, goal_id):
    try:
        obj = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        return render(request, 'ogunsoladebayoscrumy/exception.html', {'error': 'A record with that goal id does not exist'})
    else:
        return HttpResponse(obj.goal_name)


def add_goal(request):
    status = GoalStatus.objects.get(status_name='Daily Goal')
    user = User.objects.get(username='louis')
    ScrumyGoals.objects.create(goal_name='Keep Learning Django', goal_id=randint(
        1000, 9999), created_by='Louis', moved_by='Louis', goal_status=status, user=user)
    return HttpResponse('Done')


def home(request):
    weekly_status = GoalStatus.objects.get(status_name='Weekly Goal')
    daily_status = GoalStatus.objects.get(status_name='Daily Goal')
    verify_status = GoalStatus.objects.get(status_name='Verify Goal')
    done_status = GoalStatus.objects.get(status_name='Done Goal')

    users = User.objects.all()

    weekly_goals = weekly_status.scrumygoals_set.all()
    daily_goals = daily_status.scrumygoals_set.all()
    verify_goals = verify_status.scrumygoals_set.all()
    done_goals = done_status.scrumygoals_set.all()

    data = {'users': users, 'weekly_goals': weekly_goals, 'daily_goals': daily_goals,
            'verify_goals': verify_goals, 'done_goals': done_goals}

    return render(request, 'ogunsoladebayoscrumy/home.html', data)

ogunsoladebayoscrumy/views.py
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from .models import User, ScrumyGoals, ScrumyHistory, GoalStatus
from random import randint
from .forms import SignupForm, CreateGoalForm, MoveGoalForm
from django.contrib.auth import hashers
from django.contrib.auth.models import Group
from django.views.decorators.csrf import csrf_exempt

import json

# Create your views here.


def index(request):
    group = Group.objects.get(name='Developer')
    success = False
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.password = hashers.make_password(
                form.cleaned_data['password'])
            new_user.save()
            group.user_set.add(new_user)
            success = True
        else:
            success = False
    else:
        form = SignupForm()
    return render(request, 'ogunsoladebayoscrumy/index.html', {'form': form, 'success': success})


def move_goal(request, goal_id):
    success = False
    user = request.user
    role = Group.objects.get(user=user)
    obj = ScrumyGoals.objects.get(goal_id=goal_id)
    goal_user = str(obj.user)

    if request.method == 'POST':
        form = MoveGoalForm(request.POST, user=user, role=str(role), goal_user=goal_user)
        if form.is_valid():
            status = form.cleaned_data['goal_status']
            obj.goal_status = status
            obj.save()
            success = True
        else:
            success = False
    else:
        form = MoveGoalForm(user=user, role=str(role), goal_user=goal_user)
    return render(request, 'ogunsoladebayoscrumy/movegoal.html', {'form': form, 'success': success, 'role': str(role), 'goal': obj})


def add_goal(request):
    success = False
    user = request.user
    role = Group.objects.get(user=user)

    if request.method == 'POST':
        form = CreateGoalForm(request.POST, user=user)
        if form.is_valid():
            new_goal = form.save(commit=False)
            new_goal.goal_id = randint(1000, 9999)
            form.save()
            success = True
        else:
            print(form.errors)
            success = False
            return HttpResponse(form.errors)
    else:
        form = CreateGoalForm(user=user)
    return render(request, 'ogunsoladebayoscrumy/addgoal.html', {'form': form, 'success': success, 'role': role})


def home(request):
    user = request.user
    role = Group.objects.get(user=user)
    weekly_status = GoalStatus.objects.get(status_name='Weekly Goal')
    daily_status = GoalStatus.objects.get(status_name='Daily Goal')
    verify_status = GoalStatus.objects.get(status_name='Verify Goal')
    done_status = GoalStatus.objects.get(status_name='Done Goal')

    users = User.objects.all()

    weekly_goals = weekly_status.scrumygoals_set.all()
    daily_goals = daily_status.scrumygoals_set.all()
    verify_goals = verify_status.scrumygoals_set.all()
    done_goals = done_status.scrumygoals_set.all()

    data = {'role': role, 'users': users, 'weekly_goals': weekly_goals, 'daily_goals': daily_goals,
            'verify_goals': verify_goals, 'done_goals': done_goals}

    return render(request, 'ogunsoladebayoscrumy/home.html', data)

@csrf_exempt
def slack(request):
    body_unicode = request.body.decode('utf-8')
    body_data = json.loads(body_unicode)
    return JsonResponse({"challenge": body_data["challenge"]}, safe=False)

templates/ogunsoladebayoscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Add Goal</title>
		<link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css" />
	</head>
	<body>
		<div style="padding: 2px;">
			<ul class="nav nav-pills flex-column col-sm-2" >
				<li class="nav-item">
					<a class="nav-link active"> <b style="color:#66ffd9" > User: </b> {{user}} <b style="color:#66ffd9"> As: </b> {{role}}</a>
				</li>			
			</ul>
			<div align='right' style="margin-top: -30px;">
				<a href="{% url 'ogunsoladebayoscrumy:addgoal' %}"><button type='button' class='btn btn-link'> Add a new goal</button></a> 
			</div>
		</div>
        {% if success == True %}
            <div style="margin: 8px" class="alert alert-dismissible alert-info col-sm-4">
                <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                <strong> Goal added Successfully </strong>
            </div>
        {% endif %}
		<div>
			<form method="post">
				{% csrf_token %}
				<fieldset>
                    <legend style="margin:20px"> Add Goal </legend>
                    <div class='col-sm-4'>
                        <div class="form-group">
                            <label for="goalName">Goal Name:</label>
                            {{ form.goal_name }}
                        </div>
                        <div class="form-group">
                            <label for="user">Select User</label>
                            {{ form.user }}
                        </div>
                        <div class="form-group">
                            <label for="created-by">Created By:</label>
                            {{ form.created_by }}
                        </div>
                        <div class="form-group">
                            <label for="owner">Owner:</label>
                            {{ form.owner }}
                        </div>
                        <div class="form-group">
                            <label for="status">Select a status</label>
                            {{ form.goal_status }}
                        </div>
                        <input class="btn btn-primary" type="submit" value="Add Goal">
                    </div>
				</fieldset>
			</form>
			{% if form.errors %}
                <div style="margin: 8px" class="alert alert-dismissible alert-danger col-sm-4">
                    <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                    <strong>Error!</strong> please fill the form correctly.
                </div>
            {% endif %}
		</div>
        <a href="/ogunsoladebayoscrumy/accounts/login"><button type='button' class='btn btn-link'> Login</button></a> 

	</body>
</html>

templates/ogunsoladebayoscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>move goal</title>
</head>
<body>
    <p>{{error}}</p>
</body>
</html>

templates/ogunsoladebayoscrumy/home.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>My Scrumy</title>
		<link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
	</head>
	<body>
		<div style="padding: 2px;">
			<ul class="nav nav-pills flex-column col-sm-3" >
				<li class="nav-item">
					<a class="nav-link active"> <b style="color:#66ffd9" > User: </b> {{user}} <b style="color:#66ffd9"> As: </b> {{role}}</a>
				</li>			
			</ul>
			<div align='right' style="margin-top: -30px;">
				<a href="{% url 'ogunsoladebayoscrumy:addgoal' %}"><button type='button' class='btn btn-link'> Add a new goal</button></a> 
			</div>
		</div>
		<div>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>User</th>
						<th>Weekly Goals</th>
						<th>Daily Goals</th>
						<th>Verify Goals</th>
						<th>Done Goals</th>
					</tr>
				</thead>
				{% for user in users %}				
					<tr>
						<td>{{user.username}}</td>
						<td>
							<ul>
								{% for weekly_goal in weekly_goals %}
									{% if weekly_goal.user == user %}
										<li>
											{{weekly_goal.goal_id}}: {{weekly_goal.goal_name}}
											<a href=" {% url 'ogunsoladebayoscrumy:movegoal' weekly_goal.goal_id %} ">move</a>
										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</td>
						<td>
							<ul>
								{% for daily_goal in daily_goals %}
									{% if daily_goal.user == user %}
										<li>
											{{daily_goal.goal_id}}: {{daily_goal.goal_name}}
											<a href=" {% url 'ogunsoladebayoscrumy:movegoal' daily_goal.goal_id %} ">move</a>
										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</td>
						<td>
							<ul>
								{% for verify_goal in verify_goals %}
									{% if verify_goal.user == user %}
										<li>
											{{verify_goal.goal_id}}: {{verify_goal.goal_name}}
											<a href=" {% url 'ogunsoladebayoscrumy:movegoal' verify_goal.goal_id %} ">move</a>
										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</td>
						<td>	
							<ul>
								{% for done_goal in done_goals %}
									{% if done_goal.user == user %}
										<li>
											{{done_goal.goal_id}}: {{done_goal.goal_name}}
											<a href=" {% url 'ogunsoladebayoscrumy:movegoal' done_goal.goal_id %} ">move</a>
										</li>
									{% endif %}
								{% endfor %}
							</ul>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
		<a href="/ogunsoladebayoscrumy/accounts/login"><button type='button' class='btn btn-link'> Login</button></a> 
	</body>
</html>

templates/ogunsoladebayoscrumy/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Sign Up</title>
		<link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
	</head>
	<body>
        {% if success == True %}
            <div style="margin: 8px" class="alert alert-dismissible alert-info col-sm-4">
                <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                <strong> Your account has been created successfully </strong>
            </div>
        {% endif %}
		<div>
			<form method="post">
				{% csrf_token %}
                <fieldset>
                    <legend style="margin:20px"> Sign Up </legend>
                    <div class='col-sm-4'>
                        <div class="form-group">
                            <label for="goalName">First Name:</label>
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            <label for="user">Last Name:</label>
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            <label for="goalName">Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="goalName">Username:</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            <label for="goalName">Password:</label>
                            {{ form.password }}
                        </div>
                        <input class="btn btn-primary" type="submit" value="Sign Up" />
                    </div>                                        
                </fieldset>
			</form>
			{% if form.errors %}
                <div style="margin: 8px" class="alert alert-dismissible alert-danger col-sm-4">
                    <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                    <strong>Error!</strong> please fill the form correctly.
                </div>
            {% endif %}
		</div>
		<a href="/ogunsoladebayoscrumy/accounts/login"><button type='button' class='btn btn-link'> Login</button></a> 
	</body>
</html>

templates/ogunsoladebayoscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Move Goal</title>
		<link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css" />
	</head>
	<body>
		<div style="padding: 2px;">
			<ul class="nav nav-pills flex-column col-sm-3" >
				<li class="nav-item">
					<a class="nav-link active"> <b style="color:#66ffd9" > User: </b> {{user}} <b style="color:#66ffd9"> As: </b> {{role}}</a>
				</li>			
			</ul>
			<div align='right' style="margin-top: -30px;">
				<a href="{% url 'ogunsoladebayoscrumy:addgoal' %}"><button type='button' class='btn btn-link'> Add a new goal</button></a> 
			</div>
		</div>
        <div align="right">
            <button class="btn btn-link"><a href="{% url 'ogunsoladebayoscrumy:home' %}">Home</a></button>
        </div>
        {% if role == 'Owner' and user != goal.user or role == 'Developer' and user != goal.user %}
            <div style="margin: 8px" class="alert alert-dismissible alert-danger col-sm-4">
                <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                <strong>Error!</strong> You are not authorized to move this goal.
            </div>
        {% endif %}
        {% if success == True %}
            <div style="margin: 8px" class="alert alert-dismissible alert-info col-sm-4">
                <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                <strong> Goal moved successfully </strong>
            </div>
        {% endif %}
		<div>
			<form method="post">
				{% csrf_token %}
				<fieldset>
                    <legend style="margin:20px"> Move Goal </legend>
                    <div class='col-sm-4'>
                        <div class="form-group">
                            <label for="status"><b>Goal name</b>: {{goal.goal_name}} </label>
                        </div>
                        <div class="form-group">
                            <label for="status"><b> Goal ID</b>: {{goal.goal_id}} </label>
                        </div>
                        <div class="form-group">
                            <label for="status">Select a status</label>
                            {{ form.goal_status }}
                        </div>
                        <input class="btn btn-primary" type="submit" value="Move Goal">
                    </div>
				</fieldset>
			</form>
			{% if form.errors %}
                <div style="margin: 8px" class="alert alert-dismissible alert-danger col-sm-4">
                    <button type="button" class="close" onclick= data-dismiss="alert">&times;</button>
                    <strong>Error!</strong> please fill the form correctly.
                </div>
            {% endif %}
		</div>
		<a href="/ogunsoladebayoscrumy/accounts/login"><button type='button' class='btn btn-link'> Login</button></a> 
	</body>
</html>